In [4]:
import numpy as np

In [5]:
myList = [1,2,3]

In [6]:
np.array(myList)

array([1, 2, 3])

In [7]:
nested_list = [[1,2],[3,4],[5,6]]

In [8]:
np.array(nested_list)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
# arange is similar to python's range
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
# get a vector populated with zeros
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
# similarly for 1s
np.ones((4,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# include the stopping point 10, hence use 21
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [17]:
# create an identity matrix
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
# create random stuff
np.random.rand(2)


array([0.11469511, 0.4546659 ])

In [19]:
# random matrix
np.random.rand(5,5)

array([[0.25120509, 0.76086927, 0.47853075, 0.57488254, 0.39117999],
       [0.81644159, 0.1913242 , 0.30168239, 0.86004227, 0.78567519],
       [0.05543736, 0.3663438 , 0.50295926, 0.25195719, 0.20518926],
       [0.21967898, 0.31468166, 0.74370831, 0.44313607, 0.29449294],
       [0.26444612, 0.3723172 , 0.09412587, 0.84061748, 0.0513259 ]])

In [20]:
np.random.randint(1,100,(2,3))


array([[48,  5, 41],
       [61, 58, 18]])

In [23]:
# how to do we achieve uniform randomness?
# i.e. everytime i run this notebook I will get the same random value
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [24]:
# the seed does not affect subsequent calls
np.random.rand(4)



array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [25]:
# sample array
arr = np.arange(25)
# random array
ranarr = np.random.randint(0,50,10)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [31]:
# reshaping a 1d array using appropriate dimensions...
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr.max()


43

In [33]:
ranarr.argmax()

7

In [34]:
ranarr.min()

1

In [35]:
ranarr.argmin()

5

In [36]:
ranarr.dtype

dtype('int64')

In [37]:
arr.dtype

dtype('int64')

In [38]:
myarray = np.random.rand(4)

In [39]:
myarray

array([7.78765841e-04, 9.92211559e-01, 6.17481510e-01, 6.11653160e-01])

In [40]:
myarray.dtype

dtype('float64')