In [2]:
import numpy as np
arr = np.arange(0,11)

## Numpy Indexing

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[4]

4

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

### Broadcasting values

In [7]:
arr[:5] = 100

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
# reset
arr = np.arange(0,11)

### Slicing arrays

In [11]:
# slicing an array gives a pointer to the sliced part
slice_of_arr = arr[0:5]

In [12]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [13]:
# broadcasting the sliced array affects original
slice_of_arr[:] = 99


In [14]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [15]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [17]:
# to not affect original, the arr must be copied before being sliced...
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [22]:
# as we can see, the og is not affected
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

### 2D array indexing

In [23]:
arr_2D = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
arr_2D.shape

(3, 3)

#### Grabbing the column & rows


In [26]:
# row
arr_2D[0]
# a single elem value
arr_2D[1,1]

25

#### Slicing

In [28]:
arr_2D[:2,1:]

array([[10, 15],
       [25, 30]])

#### Conditional selection / filtering



In [29]:
arr = np.arange(0,11)

In [30]:
# have some comparison operator which returns a bool arr
bool_arr = arr > 4

In [31]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [32]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

#### More pythonic version...


In [33]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])